[package]
name = "knowledge-base"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"

diesel = {version = "2.2.0", features = ["mysql", "r2d2", "chrono"]}
chrono = { version = "0.4.39", features = ["serde"] }
utoipa = "4.2.3"
utoipa-swagger-ui = { version = "7.1.0", features = ["actix-web"] }


tokio = { version = "1.39.3", features = ["full"] }

serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

uuid = { version = "1.11.1", features = ["v4"]}

jsonwebtoken = "9.3.0"
futures-util = "0.3.30"

dotenvy = "0.15.0"
