version: "4.0"
services:
  knowledge-base:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-base
    image: rust:1.83.0
    restart: unless-stopped
    ports:
      - "80:7979"
    volumes:
      - /usr/local/rust/knowledge-base:/usr/knowledge-base
#    command:
#      - "diesel migration run"
    networks:
      - knowledge
    depends_on:
      - mysql8
      - redis7

  mysql8:
    container_name: mysql8
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqlconf:/etc/mysql
    env_file:
      - mysql.env
    networks:
      - knowledge
  redis7:
    container_name: redis7
    image: redis:7.0.5
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=&=${REDIS_PASSWORD}
    command: ["redis-server","--requirepass","${REDIS_PASSWORD}"]
    networks:
      - knowledge
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - knowledge
volumes:
  mysqldata:
  mysqlconf:
  portainer_data:
networks:
  knowledge:




