version: "4.0"
services:
  knowledge-base:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-base
    image: rust:1.83.0
    restart: unless-stopped
    ports:
      - "80:7979"
    volumes:
      - /usr/local/rust/knowledge-base:/usr/knowledge-base
    command:
      - "diesel migration run"
    networks:
      - knowledge
    depends_on:
      - mysql8

  mysql8:
    container_name: mysql8
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqlconf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=226688wei.
    networks:
      - knowledge
volumes:
  mysqldata:
  mysqlconf:
networks:
  knowledge:




