version: "4.0"
services:
  knowledge-base:
    container_name: knowledge-base
    image: rust:1.83.0
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - /usr/local/rust:/usr
    command:
      - apt-get install libmariadb-dev-compat -y
    networks:
      - knowledge

  mysql8:
    container_name: mysql8
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/mysql:/var/lib/mysql
      - /user/local/mysqletc:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=226688wei.
    networks:
      - knowledge
networks:
  knowledge:




