version: "4.0"
services:
  knowledge-base:
    container_name: knowledge-base
    image: rust:1.83.0
    restart: unless-stopped
    ports:
      - "7979:7979"
    volumes:
      - /usr/local/rust:/usr
    networks:
      - knowledge

  mysql8:
    container_name: mysql8
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - mysqlconf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=226688wei.
    command: ["sh","-c","docker-entrypoint.sh mysqld"]
    networks:
      - knowledge
volumes:
  mysqldata:
  mysqlconf:
networks:
  knowledge:




